!*********/files/**************************
      integer*4 isfileopen
      CHARACTER*256 CONFIG,schFile,THMOFILE,FILEIN,outfil,hydroPFile,DiffGibbsFile
      character*256 inputMineralFile,BulkRockCompositionFile
      common /files/CONFIG,schFile,thmoFile,filein,outfil,hydroPFile,DiffGibbsFile,inputMineralFile,isfileopen,   &
      		bulkrockcompositionfile
!***********************************
